### ISSUE TITLE
Relax dependendencies

### ISSUE THREAD

**Issue by Matt-Yorkley** [ddoherty03/fat_table#4]
Hi @ddoherty03, I've just started playing with `fat_table` and it's really great. Would it be possible to relax some of the dependencies in the gemfile?

It requires all of the following database adapters to be installed, but I'm only using `pg`. It's likely that users will only use one at a time, right?

https://github.com/ddoherty03/fat_table/blob/5a90abb3d3ed320519099a7f0e2578680bdd5c5a/fat_table.gemspec#L80-L84

Likewise with the build requirement for installing all three of these packages:

```
libsqlite3-dev
libpq-dev
libmysqlclient-dev
```

**Comment by ddoherty03** [comment]
When I get a chance, I will take a look at doing so.  I only use postgres
as well, so maybe I'll just restrict it to that.

Do you know of how other gems deal with this?

Thanks for taking a look at fat_table.

**Comment by ddoherty03** [comment]
Try the new version.  If that works, I'll close this.
